### ISSUE TITLE
sdkmain.io step of the deployment fails

### ISSUE THREAD

**Issue by fichmann** [aws-samples/serverless-eda-insurance-claims-processing#60]
While running npm deploy, bunch of errors come during the 
curl -s "https://get.sdkman.io" | bash;     bash -c "source $HOME/.sdkman/bin/sdkman-init.sh;     sdk install maven;     sdk install java 17.0.8-amzn;"

not able to identify the root cause. 

Tried in both Cloud9 w/ Amazon Linux and Ubuntu 22.04

Dockerfile:6
--------------------
   5 |     
   6 | >>> RUN \
   7 | >>>     curl -s "https://get.sdkman.io" | bash; \
   8 | >>>     bash -c "source $HOME/.sdkman/bin/sdkman-init.sh; \
   9 | >>>     sdk install maven; \
  10 | >>>     sdk install java 17.0.8-amzn;"
  11 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c curl -s \"https://get.sdkman.io\" | bash;     bash -c \"source $HOME/.sdkman/bin/sdkman-init.sh;     sdk install maven;     sdk install java 17.0.8-amzn;\"" did not complete successfully: exit code: 1

 ❌ Deployment failed: Error: Failed to build asset 31c07a5ee4d6dadbbc208bcaf57ca6caf094fa85580829d3992c970545196b17:current_account-current_region
    at Deployments.buildSingleAsset (/home/ubuntu/.nvm/versions/node/v20.13.1/lib/node_modules/aws-cdk/lib/index.js:443:11302)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.buildAsset (/home/ubuntu/.nvm/versions/node/v20.13.1/lib/node_modules/aws-cdk/lib/index.js:443:197148)
    at async /home/ubuntu/.nvm/versions/node/v20.13.1/lib/node_modules/aws-cdk/lib/index.js:443:181290

Failed to build asset 31c07a5ee4d6dadbbc208bcaf57ca6caf094fa85580829d3992c970545196b17:current_account-current_region

**Comment by fichmann** [comment]
I found the problem, sdk is trying to run "sdk install java 17.0.8-amzn" but this version is no longer available, so I changed to 17.0.11 and worked

**Comment by smoell** [comment]
Thank you, I'll fix this!
